=== 123inkt/123view/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- definition of configuration -->
    <xs:element name="configuration">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="repositories"/>
                <xs:element ref="rule" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- definition of repositories -->
    <xs:element name="repositories">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="repository" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- definition of repository -->
    <xs:element name="repository">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="name" type="xs:string" use="required"/>
                    <xs:attribute name="url" type="xs:string" use="required"/>
                    <xs:attribute name="upsource-project-id" type="xs:string"/>
                    <xs:attribute name="gitlab-project-id" type="xs:integer"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <!-- definition of rule -->
    <xs:element name="rule">
        <xs:complexType>
            <xs:all>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="repositories">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="repository" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="name" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="recipients"/>
                <xs:element name="subject" type="xs:string" minOccurs="0"/>
                <xs:element ref="external_links" minOccurs="0"/>
                <xs:element ref="include" minOccurs="0"/>
                <xs:element ref="exclude" minOccurs="0"/>
            </xs:all>
            <xs:attributeGroup ref="ruleAttributeGroup"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of recipients -->
    <xs:element name="recipients">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="recipient" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- definition of recipient -->
    <xs:element name="recipient">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="email" type="emailAddress" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of external_links -->
    <xs:element name="external_links">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="external_link" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- definition of external_link -->
    <xs:element name="external_link">
        <xs:complexType>
            <xs:attribute name="pattern" type="xs:string" use="required"/>
            <xs:attribute name="url" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of include -->
    <xs:element name="include">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="subject" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="file" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="author" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- definition of exclude -->
    <xs:element name="exclude">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="subject" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="file" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="author" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- email type -->
    <xs:simpleType name="emailAddress">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^@]+@[^.]+\..+"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- theme types -->
    <xs:simpleType name="themeTypes">
        <xs:restriction base="xs:string">
            <xs:enumeration value="upsource"/>
            <xs:enumeration value="darcula"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- mail frequencies -->
    <xs:simpleType name="frequencyTypes">
        <xs:restriction base="xs:string">
            <xs:enumeration value="once-per-hour"/>
            <xs:enumeration value="once-per-two-hours"/>
            <xs:enumeration value="once-per-three-hours"/>
            <xs:enumeration value="once-per-four-hours"/>
            <xs:enumeration value="once-per-day"/>
            <xs:enumeration value="once-per-week"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- diff algorithm types: see https://git-scm.com/docs/git-diff -->
    <xs:simpleType name="diffAlgorithmTypes">
        <xs:restriction base="xs:string">
            <xs:enumeration value="patience"/>
            <xs:enumeration value="minimal"/>
            <xs:enumeration value="histogram"/>
            <xs:enumeration value="myers"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- git log settings: see https://git-scm.com/docs/git-log -->
    <xs:attributeGroup name="ruleAttributeGroup">
        <xs:attribute name="active" type="xs:boolean" default="true"/>
        <xs:attribute name="theme" type="themeTypes" default="upsource"/>
        <xs:attribute name="frequency" type="frequencyTypes" default="once-per-hour"/>
        <xs:attribute name="diffAlgorithm" type="diffAlgorithmTypes" default="histogram"/>
        <xs:attribute name="excludeMergeCommits" type="xs:boolean" default="true"/>
        <xs:attribute name="ignoreSpaceAtEol" type="xs:boolean" default="true"/>
        <xs:attribute name="ignoreSpaceChange" type="xs:boolean" default="false"/>
        <xs:attribute name="ignoreAllSpace" type="xs:boolean" default="false"/>
        <xs:attribute name="ignoreBlankLines" type="xs:boolean" default="false"/>
    </xs:attributeGroup>
</xs:schema>

=== 123inkt/123view/tests/Data/Integration/Service/Config/ConfigLoaderTest/valid-config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="../../../../../../config.xsd">
    <repositories>
        <repository name="sherlock-repository"
                    url="https://gitlab.example.com/sherlock/holmes.git"
                    upsource-project-id="upsource"
                    gitlab-project-id="5"/>
    </repositories>
    <rule diffAlgorithm="patience"
          ignoreAllSpace="true"
          ignoreBlankLines="true"
          ignoreSpaceAtEol="false"
          ignoreSpaceChange="true"
          excludeMergeCommits="false"
          theme="upsource"
          frequency="once-per-hour"
    >
        <name>Example rules</name>
        <repositories>
            <repository name="sherlock-repository"/>
        </repositories>
        <recipients>
            <recipient email="sherlock@example.com" name="Sherlock Holmes"/>
        </recipients>
        <subject>subject</subject>
        <external_links>
            <external_link pattern="B#{}" url="https://example.com/entity/id/{}"/>
            <external_link pattern="US#{}" url="https://example.com/entity/id/{}"/>
        </external_links>
        <exclude>
            <subject>subject</subject>
            <file>file</file>
            <author>author</author>
        </exclude>
    </rule>
</configuration>

=== 123inkt/123view/tests/Data/E2E/MailCommandTest/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="../../../../config.xsd">
    <repositories>
        <repository name="sherlock" url="https://example.com/detectives/sherlock.git"/>
    </repositories>
    <rule theme="darcula">
        <name>Detectives</name>
        <subject>My commits</subject>
        <external_links>
            <external_link pattern="B#{}" url="https://example.com/detectives/issue/{}"/>
        </external_links>
        <repositories>
            <repository name="sherlock"/>
        </repositories>
        <recipients>
            <recipient email="sherlock@example.com" name="Sherlock Holmes"/>
        </recipients>
    </rule>
</configuration>

=== 123inkt/123view/tests/Data/Unit/Service/Config/ConfigValidatorTest/valid-config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="../../../../../../config.xsd">
    <repositories>
        <repository name="sherlock" url="https://gitlab.example.com/sherlock/holmes.git"/>
    </repositories>
    <rule>
        <name>Example rules</name>
        <repositories>
            <repository name="sherlock"/>
        </repositories>
        <recipients>
            <recipient email="sherlock@example.com" name="Sherlock Holmes"/>
        </recipients>
    </rule>
</configuration>
